# openapi2-functions.yaml
swagger: '2.0'
info:
  title: API pedidos
  description: API pedidos Semana 6
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /api/enviosdelosalpes/webhook:
    post:
      summary: Obtiene la lista de heroes
      operationId: heroes-list
      x-google-backend:
        address: https://us-central1-miso-my-first-project-339515.cloudfunctions.net/estado_pago_actualizacion 
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /api/pagosdelosalpes/webhook:
    post:
      summary: Webhook proveedor de pagos
      operationId: heroes-detail
      x-google-backend:
        address: https://us-central1-miso-my-first-project-339515.cloudfunctions.net/estado_pago_actualizacion  
      responses:
        '200':
          description: A successful response
          schema:
            type: string

#gcloud api-gateway apis create miso-my-first-project-339515
# gcloud api-gateway api-configs create miso-my-first-project-339515-api-config --api=miso-my-first-project-339515-api --openapi-spec=./api-gateway.yml
# gcloud api-gateway gateways create miso-my-first-project-339515-gateway --api=miso-my-first-project-339515-api --api-config=miso-my-first-project-339515-api-config --location=us-central1